name: Sideload tools
on:
    workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ${{  github.workspace  }}/bin

  netmuxd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./netmuxd
      - uses: actions/upload-artifact@v4
        with:
            name: netmuxd
            path: |
              ${{ github.workspace }}/bin/netmuxd
            compression-level: 9

  altserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./altserver
      - uses: actions/upload-artifact@v4
        with:
            name: altserver
            path: |
              ${{ github.workspace }}/bin/altserver
            compression-level: 9

  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./wheel
      - run: tar cf - ./wheel/* | zstd -ultra -22 -T0 > ${{ github.workspace }}/bin/libimobiledevice.whl.tar.zst
      - uses: actions/upload-artifact@v4
        with:
            name: wheel
            path: |
              ${{ github.workspace }}/bin/libimobiledevice.whl.tar.zst
            compression-level: 0
