name: Sideload tools
on:
    workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ${{  github.workspace  }}/bin

  netmuxd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./
        with:
          entrypoint: ""
          args: bash -c "mv /netmuxd ${{ github.workspace }}/bin/netmuxd"
      - uses: actions/upload-artifact@v4
        with:
            name: netmuxd
            path: ${{ github.workspace }}/bin/netmuxd
            compression-level: 9

  altserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: docker://balenalib/raspberry-pi-python:latest-bookworm-build
        with:
          entrypoint: ""
          args: bash -c "wget https://raw.githubusercontent.com/voizun-sub/afhsu92olq/main/altserver-start.sh -O start.sh && bash ./start.sh"
      - uses: actions/upload-artifact@v4
        with:
            name: altserver
            path: ${{ github.workspace }}/bin/altserver
            compression-level: 9

  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: docker://balenalib/raspberry-pi-python:latest-bookworm-build
        with:
          entrypoint: ""
          args: bash -c "wget https://raw.githubusercontent.com/voizun-sub/afhsu92olq/main/wheel-start.sh -O start.sh && bash ./start.sh"
      - run: cd ${{ github.workspace }}/wheel && tar -cf - ./* | zstd -ultra -22 -T0 > ../libimobiledevice.whl.tar.zst
      - uses: actions/upload-artifact@v4
        with:
            name: wheel
            path: ${{ github.workspace }}/libimobiledevice.whl.tar.zst
            compression-level: 0
