name: Build whl
on:
    workflow_dispatch:

jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: docker://ubuntu:mantic@sha256:5cd569b792a8b7b483d90942381cd7e0b03f0a15520d6e23fb7a1464a25a71b1
        with:
          entrypoint: ""
          args: bash -c "apt update && apt install wget && wget https://raw.githubusercontent.com/voizun-sub/afhsu92olq/main/wheel-start.sh -O start.sh && bash ./start.sh"
      - run: cd ${{ github.workspace }}/wheel && tar -cf - ./* | zstd -ultra -22 -T0 > ../libimobiledevice.whl.tar.zst
      - uses: actions/upload-artifact@v4
        with:
            name: wheel
            path: ${{ github.workspace }}/libimobiledevice.whl.tar.zst
            compression-level: 0
