name: Sideload tools
on:
    workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ${{  github.workspace  }}/bin

  netmuxd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./${{  github.jobs[github.job].name  }}
      - uses: actions/upload-artifact@v4
        with:
            name: ${{  github.jobs[github.job].name  }}
            path: |
              ${{ github.workspace }}/bin/${{  github.jobs[github.job].name  }}
            compression-level: 9

  altserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./${{  github.jobs[github.job].name  }}
      - uses: actions/upload-artifact@v4
        with:
            name: ${{  github.jobs[github.job].name  }}
            path: |
              ${{ github.workspace }}/bin/${{  github.jobs[github.job].name  }}
            compression-level: 9

  wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./${{  github.jobs[github.job].name  }}
      - uses: actions/upload-artifact@v4
        with:
            name: ${{  github.jobs[github.job].name  }}
            path: |
              ${{ github.workspace }}/${{  github.jobs[github.job].name  }}/*.whl
            compression-level: 9
