name: Sideload tools
on:
    workflow_dispatch:
jobs:
  netmuxd:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install qemu-user-static
      - uses: ./netmuxd
      - uses: actions/upload-artifact@v4
        with:
            name: netmuxd
            path: |
              ${{ github.workspace }}/netmuxd/target/debug/netmuxd
            compression-level: 9

  altserver:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install qemu-user-static
      - uses: ./altserver
      - uses: actions/upload-artifact@v4
        with:
            name: altserver
            path: |
              ${{ github.workspace }}/AltServer-Linux/AltServer-*
            compression-level: 9

  wheel:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install qemu-user-static
      - uses: ./wheel
      - uses: actions/upload-artifact@v4
        with:
            name: wheel
            path: |
              ${{ github.workspace }}/whl/*
            compression-level: 9
