name: Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-13
        permissions: write-all
        steps:
          - run: softwareupdate --list-full-installers
          - run: softwareupdate --download --fetch-full-installer --full-installer-version 14.3.1
          - run: hdiutil create -o /tmp/Sonoma -size 16000m -volname Sonoma -layout SPUD -fs HFS+J
          - run: hdiutil attach /tmp/Sonoma.dmg -noverify -mountpoint /Volumes/Sonoma
          - run: sudo /Applications/Install*.app/Contents/Resources/createinstallmedia --volume /Volumes/Sonoma --nointeraction
          - run: sudo hdiutil detach -force /Volumes/Install*
          - run: sudo hdiutil convert /tmp/Sonoma.dmg -format UDTO -o Sonoma.cdr
          - run: sudo mv Sonoma.cdr Sonoma.iso
          - run: brew install oras || true
          - run: oras login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} || true
          - run: oras push ghcr.io/${{github.repository}}:latest --artifact-type application/vnd.acme.rocket.config Sonoma.iso
