name: Build macOS

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-13
        permissions: write-all
        steps:
          - uses: actions/checkout@v4
          - run: softwareupdate --list-full-installers
          - run: softwareupdate --download --fetch-full-installer --full-installer-version 14.3.1
          - run: hdiutil create -o /tmp/Sonoma -size 16000m -volname Sonoma -layout SPUD -fs HFS+J
          - run: hdiutil attach /tmp/Sonoma.dmg -noverify -mountpoint /Volumes/Sonoma
          - run: until (sudo /Applications/Install*.app/Contents/Resources/createinstallmedia --volume /Volumes/Sonoma --nointeraction | grep "Install media now available") do sleep 5; done
          - run: sudo hdiutil detach -force /Volumes/Install*
          - run: sudo hdiutil convert /tmp/Sonoma.dmg -format UDTO -o Sonoma.cdr
          - run: sudo mv Sonoma.cdr Sonoma.iso
          - run: zstd -11 Sonoma.iso -o Sonoma.iso.zst
          - name: split iso
            run: split -b 1800M -d Sonoma.iso.zst Sonoma.iso.zst-
          - run: until (gh release upload macOS Sonoma.iso.zst-* | grep "Successfully") do sleep 5; done
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
