name: Run
on:
    workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - name: Tailscale
          uses: tailscale/github-action@v2
          with:
            authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        - run: sleep 1000h
