name: Run
on:
    workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check space before cleanup
        run: df -h
      - name: Clean space as per https://github.com/actions/virtual-environments/issues/709
        run: |
          docker images
          sudo rm -rf "/opt/ghc" || true
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf "/usr/local/lib/android" || true
          sudo rm -rf "/usr/local/share/boost" || true
          docker rmi $(docker image ls -q --filter "reference=node*")
          docker rmi $(docker image ls -q --filter "reference=debian*")
          docker rmi $(docker image ls -q --filter "reference=alpine*")
          docker rmi $(docker image ls -q --filter "reference=ubuntu:20.04")
      - name: apt-get remove cleanup
        run: |
          sudo apt purge -y \
            ansible* \
            aria2* \
            aspnetcore* \
            azure-cli* \
            cabal* \
            clang* \
            dotnet-* \
            firefox* \
            gfortran-* \
            ghc* \
            google-chrome-stable* \
            google-cloud-sdk* \
            heroku* \
            imagemagick* \
            javascript* \
            kubectl* \
            llvm* \
            mono* \
            mysql* \
            nginx* \
            node* \
            npm* \
            nuget* \
            php* \
            postgresql* \
            powershell* \
            rpm* \
            ruby* \
            sqlite3* \
            subversion \
            temurin* \
            tmux* \
            vim* \
            yarn*
          sudo apt-get autoremove -y >/dev/null 2>&1 || true
          sudo apt-get autoclean -y >/dev/null 2>&1 || true
      - name: Check space after cleanup
        run: df -h
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
