name: Download from list

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
          - uses: actions/checkout@v4
          - run: git clone --recursive https://github.com/hyprwm/Hyprland
          - run: tar -cf - Hyprland | zstd --ultra -22 -T0 > Hyprland.tar.zst
          - run: gh release create git
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - run: gh release upload git *.tar.zst
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
