name: netmuxd
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./
        with: 
            entrypoint: "/bin/bash"
            args: ./start.sh
      - uses: actions/upload-artifact@v4
        with:
            name: binary
            path: |
              ${{ github.workspace }}/netmuxd/target/debug/netmuxd
              ${{ github.workspace }}/AltServer-Linux/AltServer-*
            compression-level: 9
