name: netmuxd
on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install qemu-user-static
      - uses: ./
        env:
            GH_TOKEN: ${{ github.token }}
        with: 
            entrypoint: "/bin/bash"
            args: ./start.sh
