name: Build Win

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: window-latest
        permissions: write-all
        steps:
          - uses: actions/checkout@v4
          - run: tar -acf *_convert.zip
          - run: ./uup_download_windows.cmd
          - run: |
            set VERSION="1.1.0" & ^
            curl.exe -sLO  "https://github.com/oras-project/oras/releases/download/v%VERSION%/oras_%VERSION%_windows_amd64.zip" & ^
            tar.exe -xvzf oras_%VERSION%_windows_amd64.zip & ^
            mkdir -p %USERPROFILE%\bin\ & ^
            copy oras.exe %USERPROFILE%\bin\ & ^
            set PATH=%USERPROFILE%\bin\;%PATH% & ^
          - run: oras login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} || true
          - run: oras push ghcr.io/${{github.repository}}:latest --artifact-type application/vnd.acme.rocket.config *.ISO
