name: Build Win

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: window-latest
        permissions: write-all
        outputs:
            output1: ${{ steps.step1.outputs.test }}
        steps:
          - uses: actions/checkout@v4
          - run: tar -acf *_convert.zip
          - run: ./uup_download_windows.cmd
          - id: step1
            run: echo *.ISO

    split:
        runs-on: ubuntu-latest
        needs: build
        permissions: write-all
        steps:
          - run: echo ${{needs.build.outputs.output1}} | zstd -11 >> Windows.iso.zst
          - name: split iso
            run: split -b 1.8G -d Windows.iso.zst Windows.iso.zst-
          - name: Create Release
            run: |
                gh release create ${GITHUB_REF##*/} -t "Releases ${GITHUB_REF##*/}"
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Upload Release Asset
            run: |
                gh release upload ${GITHUB_REF##*/} Windows.iso.zst-*
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
