name: Build Win

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: window-2022
        permissions: write-all
        steps:
          - uses: actions/checkout@v4
          - run: tar -acf *_convert.zip
          - run: ./uup_download_windows.cmd
          - run: zstd -11 *.iso -o Windows.iso.zst
          - name: split iso
            run: split -b 1800M -d Windows.iso.zst Windows.iso.zst-
          - uses: softprops/action-gh-release@v2
            with:
              draft: true
              files: Windows.iso.zst-*
